site_url: "sc-domain:tiffit.com"
spreadsheet_id: "15MMDmvatemCbrgg-QhjicHuqd0UDpVjQqMEeBOzqraU"
start_date: "2025-01-01"
end_date: "2025-05-30"

sheet_names:
  raw_data: "Raw Data"
  insights: "Insights"
  charts: "Charts"
